# See https://bookdown.org/yihui/blogdown/travis-github.html

language: r
dist: xenial
latex: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files


r_github_packages:
  - rstudio/bookdown

addons:
  apt:
    packages:
      - libgsl-dev

script:
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: book_output
  on:
    all_branches: true
