# See https://bookdown.org/yihui/blogdown/travis-github.html

language: r
dist: xenial
latex: false

cache:
  packages: yes

script:
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: book_output
