# Random Number Generation

Simulation basics.

## Exercises

### Rejection sampling
Let $f$ and $g$ be two probability densities on $(0,\infty)$, such that
\begin{align*}
  f(x) \propto \sqrt{4+x}\,x^{\theta-1} e^{-x}, \quad
  g(x) \propto (2 x^{\theta-1} + x^{\theta-1/2}) e^{-x}, \quad x>0.
\end{align*}

- Find the value of the normalizing constant for $g$, i.e.,
  the constant $C$ such that
  \begin{align*}
    C\int_0^\infty (2 x^{\theta-1} +  x^{\theta-1/2}) e^{-x} \dd x=1.
  \end{align*}
  Show that $g$ is a mixture of Gamma distributions.  Identify the
  component distributions and their weights in the mixture.
- Design a procedure (pseudo-code) to sample from $g$;
  implement it in an R function;
  draw a sample of size $n = 10,000$ using your function for at least one
  $\theta$ value; 
  plot the kernel density estimation of $g$ from your sample and the true
  density in one figure. 
- Design a procedure (pseudo-code) to use rejection sampling to sample from
  $f$ using $g$ as the instrumental distribution.  Overlay the estimated
  kernel density of a random sample generated by your procedure and $f$.

### Mixture of beta
Let $f$ be a probability density on $(0,1)$ such that
\begin{align*}
  f(x) \propto \frac{x^{\theta-1}}{1+x^2} + \sqrt{2+x^2}
  (1-x)^{\beta-1}, \quad 0<x<1.
\end{align*}

- Design a procedure (pseudo-code) to sample from $f$ using a mixture of
  Beta distributions as the instrumental density.  That is, the instrumental
  density should have the form
  \begin{align*}
    \sum_{k=1}^m p_k g_k(x),
  \end{align*}
  where $p_k$ are weights and $g_k$ are densities of Beta
  distributions.  Specify your choice of the mixture. Implement your
  algorithm in an R function. Graph the estimated density of a random sample
  of $n = 10,000$ generated by your procedure and $f$ for at least one
  $(\theta, \beta)$.
- As shown in class, $f(x)$ can also be sampled using
  rejection sampling, by dealing with the two components
  \begin{align*}
    \frac{x^{\theta-1}}{1+x^2}, \quad \sqrt{2+x^2}
    (1-x)^{\beta-1}
  \end{align*}
  separately using individual Beta distributions.  Design a procedure
  (pseudo-code) to do this; implement it with an R function; overlay the
  estimated density of a random sample of size $n = 10,000$ generated by
  your procedure and $f$.
